spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

app.jwt.secret=c2VjdXJlLWtleS1mb3Itand0LXRva2VuLWdlbmVyYXRpb24=
app.jwt.expiration=86400000

server.address=0.0.0.0

# Push: установите true и положите JSON ключа сервисного аккаунта Firebase в classpath или укажите file:...
firebase.enabled=false
firebase.credentials-json=classpath:firebase-service-account.json
